declare namespace core {
    function setJDay(jday : number) : void;
    function getJDay() : number;
    function setMJDay(mjd: number) : void;
    function getMJDay() : number;
    function setDate(s : string, s2 : string, b : boolean) : void;
    function setDate(s1 : string, s2 : string): void;
    function setDate(d : string) : void;
    function getDate(fmt : string) : string;
    function getDate() : string;
    function getDeltaT() : string;
    function getDeltaTAlgorithm() : string;
    function setDeltaTAlgorithm(s:string) : void;
    function setTimeRate(t : number) : void;
    function getTimeRate() : number;
    function isRealTime() : boolean;
    function setRealTime() : void;    
    function isPlanetocentricCalculations() : boolean;
    function setPlanetocentricCalculations(b:boolean):void;
    function selectObjectByName(s:string,b:boolean):void;
    function selectObjectByName(s:string):void;
    function getObjectPosition(s:string) : any;
    function getObjectInfo(s:string) : any;
    function getSelectedObjectInfo() : any;
    function clear(s:string) : void;
    function clear() : void;

    function getViewAltitudeAngle() : number;
    function getViewAzimuthAngle(): number 
    function getViewRaAngle(): number 
    function getViewDecAngle(): number 
    function getViewRaJ2000Angle(): number 
    function getViewDecJ2000Angle(): number 
    
    // <ibg 2018-10-24> Technically parameters 1 and 2 are originally strings. 
    // http://stellarium.org/doc/0.18/namespaceStelUtils.html#acd88f8194549c7d46656952428720427
    // I added two overloads for numbers
    function moveToAltAzi(alt:number, az:number, f : number) : void;
    function moveToAltAzi(alt:number, az:number) : void;
    // original (proper definition):
    function moveToAltAzi(s:string, s2:string, f : number) : void;
    function moveToAltAzi(s:string, s2:string) : void;
    // </ibg>

    function moveToRaDec(s:string, s2:string, f : number): void;
    function moveToRaDec(s:string, s2:string): void;
    function moveToRaDecJ2000(s:string, s2:string, f:number): void;
    function moveToRaDecJ2000(s:string, s2:string): void;
    function setObserverLocation(d1:number,d2:number,d3:number,d4:number,s1:string,s2:string):void;
    function setObserverLocation(d1:number,d2:number,d3:number,d4:number,s:string):void;
    function setObserverLocation(d1:number,d2:number,d3:number,d4:number):void;
    function setObserverLocation(d1:number,d2:number,d3:number):void;
    function setObserverLocation(s:string,f:number):void;
    function setObserverLocation(s:string):void;
    function getObserverLocation() : string;
    function getObserverLocationInfo() : any;
    function screenshot(s:string,b:boolean,s2:string,b2:boolean):void;
    function screenshot(s:string,b:boolean,s2:string):void;
    function screenshot(s:string,b:boolean):void;
    function screenshot(s:string):void;
    function setGuiVisible(b:boolean):void;
    function setMinFps(f:number):void;
    function getMinFps():number;
    function setMaxFps(f:number):void;
    function getMaxFps():number;
    function getMountMode():string;
    function setMountMode(s:string):void;
    function getNightMode():boolean;
    function setNightMode(b:boolean):void;
    function getProjectionMode():string;
    function setProjectionMode(s:string):void;
    function getDiskViewport():boolean;
    function setDiskViewport(b:boolean):void;
    function setSphericMirror(b:boolean):void;
    function setViewportOffset(f1:number,f2:number):void;
    function setViewportStretch(f:number):void;
    // function getAllSkyCultureIDs();
    function getSkyCulture():string;
    function setSkyCulture(s:string):void;
    function getSkyCultureName():string;
    function getSkyCultureNameI18n():string;
    function getFlagGravityLabels():boolean;
    function setFlagGravityLabels(b:boolean):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool,QString):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,QString,QString,QString,QString,QString,QString,double,double,bool,QString):void;
    // function loadSkyImage(s:string,QString,QString,QString,QString,QString,QString,QString,QString,QString,double,double,bool):void;
    // function loadSkyImage(s:string,QString,QString,QString,QString,QString,QString,QString,QString,QString,double,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,QString,QString,QString,QString,QString,QString,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,QString,QString,QString,QString,QString,QString):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,bool,QString):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,bool):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,double,double,double,double,bool,QString):void;
    // function loadSkyImage(s:string,QString,QString,QString,double,double,double,double,bool):void;
    // function loadSkyImage(s:string,QString,QString,QString,double,double,double,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,double,double,double):void;
    // function loadSkyImage(s:string,QString,QString,QString,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,double,double,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,double,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,bool):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double):void;
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double):void;
    function removeSkyImage(s:string):void;
    // function getScreenXYFromAltAzi(s:string,QString);
    // function loadSound(s:string,QString);
    function playSound(s:string):void;
    function pauseSound(s:string):void;
    function stopSound(s:string):void;
    function dropSound(s:string):void;
    function getSoundPosition(s:string):number;
    function getSoundDuration(s:string):number;
    function loadVideo(s:string,s2:string,f1:number,f2:number,b:boolean,f:number):void;
    function loadVideo(s:string,s2:string,f1:number,f2:number,b:boolean):void;
    function loadVideo(s:string,s2:string,f1:number,f2:number):void;
    function playVideo(s:string,b:boolean):void;
    function playVideo(s:string):void;
    // function playVideoPopout(s:string,float,float,float,float,float,float,float,bool):void;
    function pauseVideo(s:string):void;
    function stopVideo(s:string):void;
    function dropVideo(s:string):void;
    // function seekVideo(s:string,qlonglong,bool);
    // function seekVideo(s:string,qlonglong);
    // function setVideoXY(s:string,float,float,bool):void;
    // function setVideoXY(s:string,float,float):void;
    // function setVideoAlpha(s:string,float):void;
    // function resizeVideo(s:string,float,float);
    function showVideo(s:string,b:boolean):void;
    function showVideo(s:string):void;
    // function getVideoDuration(s:string);
    // function getVideoPosition(s:string);
    // function getScreenWidth();
    // function getScreenHeight();
    // function getScriptRate();
    function setScriptRate(d:number):void;
    function pauseScript():void;
    function setSelectedObjectInfo(s:string):void;
    function exit() : void;
    function quitStellarium() : void;
    // function getPropertyList();
    function debug(s:string) : void;
    function output(s:string) : void;
    
    // function mapToString(QVariantMap);
    // function resetOutput();
    // function saveOutputAs(s:string);
    function getAppLanguage():string;
    function setAppLanguage(s:string):void;
    function getSkyLanguage():string;
    function setSkyLanguage(s:string):void;
    function goHome():void;
    function setMilkyWayVisible(b:boolean):void;
    function setMilkyWayIntensity(d:number):void;
    function getMilkyWayIntensity():number;
    function setZodiacalLightVisible(b:boolean):void;
    function setZodiacalLightIntensity(d:number):void;
    // function getZodiacalLightIntensity();
    // function getBortleScaleIndex();
    function setBortleScaleIndex(i:number):void;
    function setDSSMode(b:boolean):void;
    // function isDSSModeEnabled();
    // function jdFromDateString(s:string,QString);
    
    function wait(t:number) : void;
    function waitFor(s1 : string, s2:string) : void;
    function waitFor(s:string) : void;
    function getEnv(s : string) : string;
}

declare namespace ConstellationMgr {
    function setFlagArt(b:boolean) : void;
    function getFlagArt() : boolean;

    function setArtFadeDuration(f:number) : void;
// function getArtFadeDuration();
    function setArtIntensity(f:number): void;
// function getArtIntensity();
    function setArtIntensityMinimumFov(d:number): void;
// function getArtIntensityMinimumFov();
    function setArtIntensityMaximumFov(d:number): void;
// function getArtIntensityMaximumFov();
// function setBoundariesColor(Vec3f): void;
// function getBoundariesColor();
    function setFlagBoundaries(b:boolean) : void;
    function getFlagBoundaries(): boolean;
    function setFlagIsolateSelected(b:boolean): void;
    function getFlagIsolateSelected(): boolean;
    function setFlagConstellationPick(b:boolean): void;
    function getFlagConstellationPick(): boolean;
// function setLinesColor(Vec3f);
// function getLinesColor();
    function setFlagLines(b:boolean): void;
    function getFlagLines():boolean;
// function setLabelsColor(Vec3f);
// function getLabelsColor();
    function setFlagLabels(b:boolean): void;
    function getFlagLabels() : boolean;
    function setFontSize(f:number):void;
    function getFontSize() : number;
// function setConstellationDisplayStyle(ConstellationMgr::ConstellationDisplayStyle);
// function getConstellationDisplayStyle();
// function getConstellationDisplayStyleString(ConstellationMgr::ConstellationDisplayStyle);
    function setConstellationLineThickness(i:number):void;
    function getConstellationLineThickness():number;
    function deselectConstellations():void;
    function selectAllConstellations():void;
}

declare namespace CustomObjectMgr {
    // function searchByEnglishName(s:string);
    // function addCustomObject(s:string,Vec3d,bool);
    // function addCustomObject(s:string,Vec3d);
    // function addCustomObject(s:string,QString,QString,bool);
    // function addCustomObject(s:string,QString,QString);
    // function addCustomObjectRaDec(s:string,QString,QString,bool);
    // function addCustomObjectRaDec(s:string,QString,QString);
    // function addCustomObjectAltAzi(s:string,QString,QString,bool);
    // function addCustomObjectAltAzi(s:string,QString,QString);
    // function removeCustomObjects();
    // function removeCustomObject(s:string);
    // function setMarkersColor(Vec3f);
    // function getMarkersColor();
    function setMarkersSize(f:number) : void;
    function getMarkersSize() : number;
}

declare namespace GridLinesMgr {
    function setFlagGridlines(b:boolean):void;
    function getFlagGridlines():boolean;
    function setFlagAzimuthalGrid(b:boolean):void;
    function getFlagAzimuthalGrid():boolean;
    // function getColorAzimuthalGrid();
    // function setColorAzimuthalGrid(Vec3f);
    function setFlagEquatorGrid(b:boolean):void;
    function getFlagEquatorGrid():boolean;
    // function getColorEquatorGrid();
    // function setColorEquatorGrid(Vec3f):void;
    function setFlagEquatorJ2000Grid(b:boolean):void;
    function getFlagEquatorJ2000Grid():boolean;
    // function getColorEquatorJ2000Grid();
    // function setColorEquatorJ2000Grid(Vec3f);
    function setFlagEclipticJ2000Grid(b:boolean):void;
    function getFlagEclipticJ2000Grid():boolean;
    // function getColorEclipticJ2000Grid();
    // function setColorEclipticJ2000Grid(Vec3f);
    function setFlagEclipticGrid(b:boolean):void;
    function getFlagEclipticGrid():boolean;
    // function getColorEclipticGrid();
    // function setColorEclipticGrid(Vec3f);
    function setFlagGalacticGrid(b:boolean):void;
    function getFlagGalacticGrid():boolean;
    // function getColorGalacticGrid();
    // function setColorGalacticGrid(Vec3f);
    function setFlagSupergalacticGrid(b:boolean):void;
    function getFlagSupergalacticGrid():boolean;
    // function getColorSupergalacticGrid();
    // function setColorSupergalacticGrid(Vec3f):void;
    function setFlagEquatorLine(b:boolean):void;
    function getFlagEquatorLine():boolean;
    // function getColorEquatorLine();
    // function setColorEquatorLine(Vec3f):void;
    function setFlagEquatorJ2000Line(b:boolean):void;
    function getFlagEquatorJ2000Line():boolean;
    // function getColorEquatorJ2000Line();
    // function setColorEquatorJ2000Line(Vec3f):void;
    function setFlagEclipticJ2000Line(b:boolean):void;
    function getFlagEclipticJ2000Line():boolean;
    // function getColorEclipticJ2000Line();
    // function setColorEclipticJ2000Line(Vec3f);
    function setFlagEclipticLine(b:boolean):void;
    function getFlagEclipticLine():boolean;
    // function getColorEclipticLine();
    // function setColorEclipticLine(Vec3f);
    function setFlagPrecessionCircles(b:boolean):void;
    function getFlagPrecessionCircles():boolean;
    // function getColorPrecessionCircles();
    // function setColorPrecessionCircles(Vec3f);
    function setFlagMeridianLine(b:boolean):void;
    function getFlagMeridianLine():boolean;
    // function getColorMeridianLine();
    // function setColorMeridianLine(Vec3f):void;
    function setFlagLongitudeLine(b:boolean):void;
    function getFlagLongitudeLine():boolean;
    // function getColorLongitudeLine();
    // function setColorLongitudeLine(Vec3f);
    function setFlagHorizonLine(b:boolean):void;
    function getFlagHorizonLine():boolean;
    // function getColorHorizonLine();
    // function setColorHorizonLine(Vec3f);
    function setFlagGalacticEquatorLine(b:boolean):void;
    function setFlagGalacticPlaneLine(b:boolean):void;
    function getFlagGalacticEquatorLine():boolean;
    function getFlagGalacticPlaneLine():boolean;
    // function getColorGalacticEquatorLine();
    // function setColorGalacticEquatorLine(Vec3f):void;
    function setFlagSupergalacticEquatorLine(b:boolean):void;
    function getFlagSupergalacticEquatorLine():boolean;
    // function getColorSupergalacticEquatorLine();
    // function setColorSupergalacticEquatorLine(Vec3f);
    function setFlagPrimeVerticalLine(b:boolean):void;
    function getFlagPrimeVerticalLine():boolean;
    // function getColorPrimeVerticalLine();
    // function setColorPrimeVerticalLine(Vec3f):void;
    function setFlagColureLines(b:boolean):void;
    function getFlagColureLines():boolean;
    // function getColorColureLines();
    // function setColorColureLines(Vec3f):void;
    function setFlagCircumpolarCircles(b:boolean):void;
    function getFlagCircumpolarCircles():boolean;
    // function getColorCircumpolarCircles();
    // function setColorCircumpolarCircles(Vec3f):void;
    function setFlagCelestialJ2000Poles(b:boolean):void;
    function getFlagCelestialJ2000Poles():boolean;
    // function getColorCelestialJ2000Poles();
    // function setColorCelestialJ2000Poles(Vec3f);
    function setFlagCelestialPoles(b:boolean):void;
    function getFlagCelestialPoles():boolean;
    // function getColorCelestialPoles();
    // function setColorCelestialPoles(Vec3f);
    function setFlagZenithNadir(b:boolean):void;
    function getFlagZenithNadir():boolean;
    // function getColorZenithNadir();
    // function setColorZenithNadir(Vec3f);
    function setFlagEclipticJ2000Poles(b:boolean):void;
    function getFlagEclipticJ2000Poles():boolean;
    // function getColorEclipticJ2000Poles();
    // function setColorEclipticJ2000Poles(Vec3f);
    function setFlagEclipticPoles(b:boolean):void;
    function getFlagEclipticPoles():boolean;
    // function getColorEclipticPoles();
    // function setColorEclipticPoles(Vec3f);
    function setFlagGalacticPoles(b:boolean):void;
    function getFlagGalacticPoles():boolean;
    // function getColorGalacticPoles();
    // function setColorGalacticPoles(Vec3f);
    function setFlagSupergalacticPoles(b:boolean):void;
    function getFlagSupergalacticPoles():boolean;
    // function getColorSupergalacticPoles();
    // function setColorSupergalacticPoles(Vec3f);
    function setFlagEquinoxJ2000Points(b:boolean):void;
    function getFlagEquinoxJ2000Points():boolean;
    // function getColorEquinoxJ2000Points();
    // function setColorEquinoxJ2000Points(Vec3f);
    function setFlagEquinoxPoints(b:boolean):void;
    function getFlagEquinoxPoints():boolean;
    // function getColorEquinoxPoints();
    // function setColorEquinoxPoints(Vec3f);
    function setFlagSolsticeJ2000Points(b:boolean):void;
    function getFlagSolsticeJ2000Points():boolean;
    // function getColorSolsticeJ2000Points();
    // function setColorSolsticeJ2000Points(Vec3f);
    function setFlagSolsticePoints(b:boolean):void;
    function getFlagSolsticePoints():boolean;
    // function getColorSolsticePoints();
    // function setColorSolsticePoints(Vec3f);
}

declare namespace LabelMgr {
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string,s4:string,d:number,s5:string,b2:boolean,i:number):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string,s4:string,d:number,s5:string,b2:boolean):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string,s4:string,d:number,s5:string):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string,s4:string,d:number):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string,s4:string):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number,s3:string):number;
    function labelObject(s:string,s2:string,b1:boolean,f:number):number;
    function labelObject(s:string,s2:string,b1:boolean):number;
    function labelObject(s:string,s2:string):number;
    
    function labelHorizon(s:string,f1:number,f2:number,b1:boolean,f3:number,s2:string,b2:boolean,i:number):number;
    function labelHorizon(s:string,f1:number,f2:number,b1:boolean,f3:number,s2:string,b2:boolean):number;
    function labelHorizon(s:string,f1:number,f2:number,b1:boolean,f3:number,s2:string):number;
    function labelHorizon(s:string,f1:number,f2:number,b1:boolean,f3:number):number;
    function labelHorizon(s:string,f1:number,f2:number,b1:boolean):number;
    function labelHorizon(s:string,f1:number,f2:number):number;
    
    function labelScreen(s:string,x:number,y:number,vis:boolean,fs:number,col:string,ad:boolean,adt:number): number;
    function labelScreen(s:string,x:number,y:number,vis:boolean,fs:number,col:string,ad:boolean): number;
    function labelScreen(s:string,x:number,y:number,vis:boolean,fs:number,col:string): number;
    function labelScreen(s:string,x:number,y:number,vis:boolean,fs:number): number;
    function labelScreen(s:string,x:number,y:number,vis:boolean): number;
    function labelScreen(s:string,x:number,y:number) : number;
    function getLabelShow(i:number):boolean;
    
    function setLabelShow(i:number,b:boolean):void;
    function setLabelText(i:number,s:string):void;
    function deleteLabel(i:number):void;
    function deleteAllLabels() : void;
}

declare namespace LandscapeMgr {
    function getLuminance():number;
    // function getAtmosphereAverageLuminance();
    function setAtmosphereAverageLuminance(f:number) : void;
    // function getNameToDirMap();
    // function getAllLandscapeNames();
    // function getAllLandscapeIDs();
    // function getUserLandscapeIDs();
    // function getCurrentLandscapeID();
    function setCurrentLandscapeID(s:string,d:number): void;
    function setCurrentLandscapeID(s:string): void;
    // function getCurrentLandscapeName();
    function setCurrentLandscapeName(s:string,d:number): void;
    function setCurrentLandscapeName(s:string): void;
    // function getCurrentLandscapeBrightness(b:boolean);
    // function getCurrentLandscapeBrightness();
    // function precacheLandscape(s:string,bool);
    // function precacheLandscape(s:string);
    // function removeCachedLandscape(s:string);
    function setCacheSize(i:number):void;
    // function getCacheSize();
    // function getCacheFilledSize();
    // function getCacheCount();
    // function getCurrentLandscape();
    // function getDefaultLandscapeID();
    function setDefaultLandscapeID(s:string):void;
    // function getCurrentLandscapeHtmlDescription();
    // function getDescription();
    function getFlagLandscape():boolean;
    function setFlagLandscape(b:boolean):void;
    // function getIsLandscapeFullyVisible();
    // function getLandscapeSinMinAltitudeLimit();
    function getFlagFog():boolean;
    function setFlagFog(b:boolean):void;
    function getFlagIllumination():boolean;
    function setFlagIllumination(b:boolean):void;
    function getFlagLabels():boolean;
    function setFlagLabels(b:boolean):void;
    function getFlagLandscapeSetsLocation():boolean;
    function setFlagLandscapeSetsLocation(b:boolean):void;
    function getFlagLandscapeUseMinimalBrightness():boolean;
    function setFlagLandscapeUseMinimalBrightness(b:boolean):void;
    function getFlagLandscapeSetsMinimalBrightness():boolean;
    function setFlagLandscapeSetsMinimalBrightness(b:boolean):void;
    // function getDefaultMinimalBrightness();
    function setDefaultMinimalBrightness(d:number):void;
    function setFlagUseLightPollutionFromDatabase(b:boolean):void;
    function getFlagUseLightPollutionFromDatabase():boolean;
    function getFlagCardinalsPoints():boolean;
    function setFlagCardinalsPoints(b:boolean):void;
    // function getColorCardinalPoints();
    //function setColorCardinalPoints(Vec3f):void;
    function getFlagAtmosphere():boolean;
    function setFlagAtmosphere(b:boolean):void;
    // function getAtmosphereFadeIntensity();
    // function getAtmosphereFadeDuration();
    function setAtmosphereFadeDuration(f:number):void;
    function setZRotation(f:number):void;
    // function installLandscapeFromArchive(s:string,bool,bool);
    // function installLandscapeFromArchive(s:string,bool);
    // function installLandscapeFromArchive(s:string);
    // function removeLandscape(s:string);
    // function loadLandscapeName(s:string);
    // function loadLandscapeSize(s:string);
    function getFlagLandscapeAutoSelection():boolean;
    function setFlagLandscapeAutoSelection(b:boolean):void;
    function getFlagEnvironmentAutoEnable():boolean;
    function setFlagEnvironmentAutoEnable(b:boolean):void;
    function getFlagAtmosphereAutoEnable():boolean;
    function setFlagAtmosphereAutoEnable(b:boolean):void;
    // function getLandscapeOpacity(Vec3d);
    // function getLandscapeOpacity(Vec3f);
    // function getLandscapeOpacity(float,float);
}

declare namespace SporadicMeteorMgr {
    //function getZHR();
    function setZHR(n:number): void;
    function setFlagShow(b:boolean) : void;
    function getFlagShow() : boolean;
    function setMaxVelocity(v:number): void;
    function setFlagForcedMeteorsActivity(b:boolean): void;
    function getFlagForcedMeteorsActivity():boolean;
}

declare namespace NebulaMgr {
    // function setCatalogFilters(Nebula::CatalogGroup);
    // function getCatalogFilters();
    // function setTypeFilters(Nebula::TypeGroup);
    // function getTypeFilters();
    // function setCirclesColor(Vec3f);
    // function getCirclesColor();
    // function setGalaxyColor(Vec3f);
    // function getGalaxyColor();
    // function setActiveGalaxyColor(Vec3f);
    // function getActiveGalaxyColor();
    // function setInteractingGalaxyColor(Vec3f);
    // function getInteractingGalaxyColor();
    // function setRadioGalaxyColor(Vec3f);
    // function getRadioGalaxyColor();
    // function setQuasarColor(Vec3f);
    // function getQuasarColor();
    // function setBrightNebulaColor(Vec3f);
    // function getBrightNebulaColor();
    // function setNebulaColor(Vec3f);
    // function getNebulaColor();
    // function setPlanetaryNebulaColor(Vec3f);
    // function getPlanetaryNebulaColor();
    // function setReflectionNebulaColor(Vec3f);
    // function getReflectionNebulaColor();
    // function setBipolarNebulaColor(Vec3f);
    // function getBipolarNebulaColor();
    // function setEmissionNebulaColor(Vec3f);
    // function getEmissionNebulaColor();
    // function setHydrogenRegionColor(Vec3f);
    // function getHydrogenRegionColor();
    // function setSupernovaRemnantColor(Vec3f);
    // function getSupernovaRemnantColor();
    // function setSupernovaCandidateColor(Vec3f);
    // function getSupernovaCandidateColor();
    // function setSupernovaRemnantCandidateColor(Vec3f);
    // function getSupernovaRemnantCandidateColor();
    // function setInterstellarMatterColor(Vec3f);
    // function getInterstellarMatterColor();
    // function setDarkNebulaColor(Vec3f);
    // function getDarkNebulaColor();
    // function setClusterWithNebulosityColor(Vec3f);
    // function getClusterWithNebulosityColor();
    // function setClusterColor(Vec3f);
    // function getClusterColor();
    // function setOpenClusterColor(Vec3f);
    // function getOpenClusterColor();
    // function setGlobularClusterColor(Vec3f);
    // function getGlobularClusterColor();
    // function setStellarAssociationColor(Vec3f);
    // function getStellarAssociationColor();
    // function setStarCloudColor(Vec3f);
    // function getStarCloudColor();
    // function setEmissionObjectColor(Vec3f);
    // function getEmissionObjectColor();
    // function setBlLacObjectColor(Vec3f);
    // function getBlLacObjectColor();
    // function setBlazarColor(Vec3f);
    // function getBlazarColor();
    // function setMolecularCloudColor(Vec3f);
    // function getMolecularCloudColor();
    // function setYoungStellarObjectColor(Vec3f);
    // function getYoungStellarObjectColor();
    // function setPossibleQuasarColor(Vec3f);
    // function getPossibleQuasarColor();
    // function setPossiblePlanetaryNebulaColor(Vec3f);
    // function getPossiblePlanetaryNebulaColor();
    // function setProtoplanetaryNebulaColor(Vec3f);
    // function getProtoplanetaryNebulaColor();
    // function setStarColor(Vec3f);
    // function getStarColor();
    // function setSymbioticStarColor(Vec3f);
    // function getSymbioticStarColor();
    // function setEmissionLineStarColor(Vec3f);
    // function getEmissionLineStarColor();
    // function setGalaxyClusterColor(Vec3f);
    // function getGalaxyClusterColor();
    // function setHintsFadeDuration(f:number);
    function setFlagHints(b:boolean):void;
    function getFlagHints():boolean;
    // function setHintsProportional(b:boolean);
    // function getHintsProportional();
    function setFlagOutlines(b:boolean):void;
    function getFlagOutlines():boolean;
    function setFlagAdditionalNames(b:boolean):void;
    function getFlagAdditionalNames():boolean;
    // function setDesignationUsage(b:boolean);
    // function getDesignationUsage();
    function setFlagSurfaceBrightnessUsage(b:boolean):void;
    function getFlagSurfaceBrightnessUsage():boolean;
    function setFlagSurfaceBrightnessArcsecUsage(b:boolean):void;
    function getFlagSurfaceBrightnessArcsecUsage():boolean;
    function setFlagSurfaceBrightnessShortNotationUsage(b:boolean):void;
    function getFlagSurfaceBrightnessShortNotationUsage():boolean;
    function setFlagSizeLimitsUsage(b:boolean):void;
    function getFlagSizeLimitsUsage():boolean;
    function setFlagShow(b:boolean):void;
    function getFlagShow():boolean;
    function setFlagUseTypeFilters(b:boolean):void;
    function getFlagUseTypeFilters():boolean;
    function setMinSizeLimit(d:number):void;
    function getMinSizeLimit():number;
    function setMaxSizeLimit(d:number):void;
    function getMaxSizeLimit():number;
    //function setLabelsColor(Vec3f):void;
    // function getLabelsColor();
    function setLabelsAmount(d:number):void;
    function getLabelsAmount():number;
    function setHintsAmount(d:number):void;
    function getHintsAmount():number;
}

declare namespace ScreenImageMgr {
    // function createScreenImage(s:string,QString,float,float,float,bool,float,float);
    // function createScreenImage(s:string,QString,float,float,float,bool,float);
    // function createScreenImage(s:string,QString,float,float,float,bool);
    // function createScreenImage(s:string,QString,float,float,float);
    // function createScreenImage(s:string,QString,float,float);
    // function getShowImage(s:string);
    // function showImage(s:string,bool);
    // function getImageWidth(s:string);
    // function getImageHeight(s:string);
    // function setImageScale(s:string,float,float,float);
    // function setImageScale(s:string,float,float);
    // function getImageScaleX(s:string);
    // function getImageScaleY(s:string);
    // function setImageAlpha(s:string,float);
    // function setImageXY(s:string,float,float,float);
    // function setImageXY(s:string,float,float);
    // function addImageXY(s:string,float,float,float);
    // function addImageXY(s:string,float,float);
    function deleteImage(s:string):void;
    function deleteAllImages():void;
    // function getAllImageIDs();
}

declare namespace SolarSystem {
    function setFlagPlanets(b:boolean) : void;
    function getFlagPlanets() : boolean;
    function setFlagTrails(b:boolean):void;
    function getFlagTrails() : boolean;
    function setFlagHints(b:boolean):void;
    function getFlagHints() : boolean;
    function setFlagLabels(b:boolean):void;
    function getFlagLabels() : boolean;
    function setLabelsAmount(d:number):void;
    // function getLabelsAmount();
    function setFlagOrbits(b:boolean):void;
    function getFlagOrbits():boolean;
    function setFlagPointer(b:boolean):void;
    function getFlagPointer():boolean;
    function setFlagLightTravelTime(b:boolean):void;
    function getFlagLightTravelTime():boolean;
    function setFlagUseObjModels(b:boolean):void;
    function getFlagUseObjModels():boolean;
    function setFlagShowObjSelfShadows(b:boolean):void;
    function getFlagShowObjSelfShadows():boolean;
    function setFontSize(f:number):void;
    //function setLabelsColor(Vec3f):void;
    // function getLabelsColor();
    //function setOrbitsColor(Vec3f):void;
    // function getOrbitsColor();
    //function setMajorPlanetsOrbitsColor(Vec3f):void;
    // function getMajorPlanetsOrbitsColor();
    //function setMoonsOrbitsColor(Vec3f):void;
    // function getMoonsOrbitsColor();
    // function setMinorPlanetsOrbitsColor(Vec3f):void;
    // function getMinorPlanetsOrbitsColor();
    // function setDwarfPlanetsOrbitsColor(Vec3f):void;
    // function getDwarfPlanetsOrbitsColor();
    // function setCubewanosOrbitsColor(Vec3f):void;
    // function getCubewanosOrbitsColor();
    // function setPlutinosOrbitsColor(Vec3f):void;
    // function getPlutinosOrbitsColor();
    // function setScatteredDiskObjectsOrbitsColor(Vec3f):void;
    // function getScatteredDiskObjectsOrbitsColor();
    // function setOortCloudObjectsOrbitsColor(Vec3f):void;
    // function getOortCloudObjectsOrbitsColor();
    // function setCometsOrbitsColor(Vec3f):void;
    // function getCometsOrbitsColor();
    // function setSednoidsOrbitsColor(Vec3f):void;
    // function getSednoidsOrbitsColor();
    // function setMercuryOrbitColor(Vec3f):void;
    // function getMercuryOrbitColor();
    // function setVenusOrbitColor(Vec3f):void;
    // function getVenusOrbitColor();
    // function setEarthOrbitColor(Vec3f):void;
    // function getEarthOrbitColor();
    // function setMarsOrbitColor(Vec3f):void;
    // function getMarsOrbitColor();
    // function setJupiterOrbitColor(Vec3f):void;
    // function getJupiterOrbitColor();
    // function setSaturnOrbitColor(Vec3f):void;
    // function getSaturnOrbitColor();
    // function setUranusOrbitColor(Vec3f):void;
    // function getUranusOrbitColor();
    //function setNeptuneOrbitColor(Vec3f):void;
    // function getNeptuneOrbitColor();
    //function setTrailsColor(Vec3f):void;
    // function getTrailsColor();
    //function setPointerColor(Vec3f):void;
    // function getPointerColor();
    function setFlagMoonScale(b:boolean):void;
    function getFlagMoonScale():boolean;
    function setMoonScale(d:number):void;
    // function getMoonScale();
    function setFlagMinorBodyScale(b:boolean):void;
    function getFlagMinorBodyScale():boolean;
    function setMinorBodyScale(d:number):void;
    // function getMinorBodyScale();
    // function updateI18n();
    // function getPlanetVMagnitude(s:string,bool);
    // function getPlanetVMagnitude(s:string);
    // function getPlanetType(s:string);
    // function getDistanceToPlanet(s:string);
    // function getElongationForPlanet(s:string);
    // function getPhaseAngleForPlanet(s:string);
    // function getPhaseForPlanet(s:string);
    function setApparentMagnitudeAlgorithmOnEarth(s:string):void;
    // function getApparentMagnitudeAlgorithmOnEarth();
    function setFlagNativePlanetNames(b:boolean):void;
    function getFlagNativePlanetNames():boolean;
    function setFlagTranslatedNames(b:boolean):void;
    function getFlagTranslatedNames():boolean;
    function setFlagIsolatedTrails(b:boolean):void;
    function getFlagIsolatedTrails():boolean;
    function setFlagIsolatedOrbits(b:boolean):void;
    function getFlagIsolatedOrbits():boolean;
    function setFlagPlanetsOrbitsOnly(b:boolean):void;
    function getFlagPlanetsOrbitsOnly():boolean;
    function setFlagCustomGrsSettings(b:boolean):void;
    function getFlagCustomGrsSettings():boolean;
    function setCustomGrsLongitude(i:number):void;
    function getCustomGrsLongitude():number;
    function setCustomGrsDrift(d:number):void;
    function getCustomGrsDrift():number;
    function setCustomGrsJD(d:number):void;
    function getCustomGrsJD():number;
    function setOrbitColorStyle(s:string):void;
    // function getOrbitColorStyle();
    // function getObjectsList(s:string);
    // function getObjectsList();
}

declare namespace StarMgr {
    // function setLabelColor(Vec3f);
    // function getLabelColor();
    function setFlagStars(b:boolean):void;
    function getFlagStars():boolean;
    function setFlagLabels(b:boolean):void;
    function getFlagLabels():boolean;
    function setLabelsAmount(d:number):void;
    // function getLabelsAmount();
    function setFontSize(f:number):void;
    function setFlagSciNames(b:boolean):void;
    function getFlagSciNames():boolean;
    function setFlagAdditionalNames(b:boolean):void;
    function getFlagAdditionalNames():boolean;
}

declare namespace StelVideoMgr {
    function init():void;
    // function update(d:number);
    // function loadVideo(s:string,QString,float,float,bool,float);
    // function playVideo(s:string,bool);
    // function playVideo(s:string);
    // function playVideoPopout(s:string,float,float,float,float,float,float,float,bool);
    // function pauseVideo(s:string);
    // function stopVideo(s:string);
    // function dropVideo(s:string);
    // function seekVideo(s:string,qlonglong,bool);
    // function seekVideo(s:string,qlonglong);
    // function setVideoXY(s:string,float,float,bool);
    // function setVideoXY(s:string,float,float);
    // function setVideoAlpha(s:string,float);
    // function resizeVideo(s:string,float,float);
    // function resizeVideo(s:string,float);
    // function resizeVideo(s:string);
    // function showVideo(s:string,bool);
    // function getVideoDuration(s:string);
    // function getVideoPosition(s:string);
    // function getVideoResolution(s:string);
    // function getVideoWidth(s:string);
    // function getVideoHeight(s:string);
    // function muteVideo(s:string,bool);
    // function muteVideo(s:string);
    // function setVideoVolume(s:string,int);
    // function getVideoVolume(s:string);
    // function isVideoPlaying(s:string);
}

declare namespace StelMovementMgr {
    // function toggleMountMode();
    function setEquatorialMount(b:boolean):void;
    function setFlagTracking(b:boolean):void;
    function setFlagTracking():void;
    function getFlagTracking():boolean;
    function setFlagLockEquPos(b:boolean):void;
    function getFlagLockEquPos():boolean;
    // function panView(double,double);
    function setAutoMoveDuration(f:number):void;
    // function getAutoMoveDuration();
    function setFlagAutoZoomOutResetsDirection(b:boolean):void;
    function getFlagAutoZoomOutResetsDirection():boolean;
    function getFlagEnableZoomKeys():boolean;
    function setFlagEnableZoomKeys(b:boolean):void;
    function getFlagEnableMoveKeys():boolean;
    function setFlagEnableMoveKeys(b:boolean):void;
    function getFlagEnableMoveAtScreenEdge():boolean;
    function setFlagEnableMoveAtScreenEdge(b:boolean):void;
    function getFlagEnableMouseNavigation():boolean;
    function setFlagEnableMouseNavigation(b:boolean):void;
    function getFlagIndicationMountMode():boolean;
    function setFlagIndicationMountMode(b:boolean):void;
    // function moveToJ2000(Vec3d,Vec3d,float,ZoomingMode);
    // function moveToJ2000(Vec3d,Vec3d,float);
    // function moveToJ2000(Vec3d,Vec3d);
    // function moveToObject(StelObjectP,float,ZoomingMode);
    // function moveToObject(StelObjectP,float);
    // function moveToObject(StelObjectP);
    // function moveToAltAzi(Vec3d,Vec3d,float,ZoomingMode);
    // function moveToAltAzi(Vec3d,Vec3d,float);
    // function moveToAltAzi(Vec3d,Vec3d);
    function zoomTo(d:number, f:number):void;
    function zoomTo(d:number):void;
    // function getCurrentFov();
    // function getInitFov();
    function setInitFov(d:number):void;
    // function getInitViewingDirection();
    // function setInitViewDirectionToCurrent();
    // function getViewDirectionJ2000();
    // function setViewDirectionJ2000(Vec3d):void;
    function setMaxFov(d:number):void;
    // function getMaxFov();
    // function getMinFov();
    // function autoZoomIn(float,bool);
    function autoZoomIn(f:number):void;
    function autoZoomIn():void;
    // function autoZoomOut(float,bool);
    function autoZoomOut(f:number):void;
    function autoZoomOut():void;
    // function getAimFov();
    // function turnRight(b:boolean);
    // function turnLeft(b:boolean);
    // function turnUp(b:boolean);
    // function turnDown(b:boolean);
    // function moveSlow(b:boolean);
    // function zoomIn(b:boolean);
    // function zoomOut(b:boolean);
    // function lookEast(b:boolean);
    // function lookEast();
    // function lookWest(b:boolean);
    // function lookWest();
    // function lookNorth(b:boolean);
    // function lookNorth();
    // function lookSouth(b:boolean);
    // function lookSouth();
    // function lookZenith();
    // function lookNadir();
    // function lookTowardsNCP();
    // function lookTowardsSCP();
    // function moveViewport(float,float,float);
    // function moveViewport(float,float);
    // function setMountMode(MountMode);
    // function getMountMode();
    // function getEquatorialMount();
    // function setInhibitAllAutomoves(b:boolean);
    // function getViewportOffsetTarget();
    // function getViewportHorizontalOffsetTarget();
    // function getViewportVerticalOffsetTarget();
    // function setViewportHorizontalOffsetTarget(f:number);
    // function setViewportVerticalOffsetTarget(f:number);
}

declare namespace StelSkyDrawer {
    function setRelativeStarScale(d:number):void;
    function setRelativeStarScale():void;
    function getRelativeStarScale():number;
    function setAbsoluteStarScale(d:number):void;
    function setAbsoluteStarScale():void;
    function getAbsoluteStarScale():number;
    function setTwinkleAmount(d:number):void;
    function getTwinkleAmount():number;
    function setFlagTwinkle(b:boolean):void;
    function getFlagTwinkle():boolean;
    function setFlagForcedTwinkle(b:boolean):void;
    function getFlagForcedTwinkle():boolean;
    function setBortleScaleIndex(i:number):void;
    // function getBortleScaleIndex();
    // function getNELMFromBortleScale();
    function setFlagDrawBigStarHalo(b:boolean):void;
    function getFlagDrawBigStarHalo():boolean;
    // function getLimitMagnitude();
    function setFlagStarMagnitudeLimit(b:boolean):void;
    function getFlagStarMagnitudeLimit():boolean;
    function setFlagNebulaMagnitudeLimit(b:boolean):void;
    function getFlagNebulaMagnitudeLimit():boolean;
    function setFlagPlanetMagnitudeLimit(b:boolean):void;
    function getFlagPlanetMagnitudeLimit():boolean;
    function getCustomStarMagnitudeLimit():number;
    function setCustomStarMagnitudeLimit(d:number):void;
    function getCustomNebulaMagnitudeLimit():number;
    function setCustomNebulaMagnitudeLimit(d:number):void;
    function getCustomPlanetMagnitudeLimit():number;
    function setCustomPlanetMagnitudeLimit(d:number):void;
    // function getLimitLuminance();
    function setFlagLuminanceAdaptation(b:boolean):void;
    function getFlagLuminanceAdaptation():boolean;
    function setDaylightLabelThreshold(d:number):void;
    // function getDaylightLabelThreshold();
    // function getWorldAdaptationLuminance();
    function setFlagHasAtmosphere(b:boolean):void;
    function getFlagHasAtmosphere():boolean;
    function setExtinctionCoefficient(d:number):void;
    // function getExtinctionCoefficient();
    function setAtmosphereTemperature(d:number):void;
    // function getAtmosphereTemperature();
    function setAtmospherePressure(d:number):void;
    // function getAtmospherePressure();
    // function getExtinction();
    // function getRefraction();
    // function getBig3dModelHaloRadius();
    function setBig3dModelHaloRadius(f:number):void;
}

declare namespace StelSkyLayerMgr {
    function setFlagShow(b:boolean) : void;
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool,StelCore::FrameType);
    // function loadSkyImage(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool);
    // function loadSkyImageAltAz(s:string,QString,double,double,double,double,double,double,double,double,double,double,bool);
    // function showLayer(s:string,bool);
    // function getShowLayer(s:string);
    // function insertSkyImage(s:string,QString,bool);
    // function insertSkyImage(s:string,QString);
    // function insertSkyImage(s:string);
    // function removeSkyLayer(s:string);
    // function getAllKeys();
}

declare namespace MilkyWay {
    function getIntensity() : number;
    function setIntensity(n:number) : void;
// function getColor();
// function setColor(Vec3f);
    function setFlagShow(b:boolean) : void;
    function getFlagShow() : boolean;
}

declare namespace ZodiacalLight {
// function getIntensity();
    function setIntensity(d:number):void;
// function getColor();
// function setColor(Vec3f);
    function setFlagShow(b:boolean) : void;
    function getFlagShow():boolean;
}

declare namespace CompassMarks {
    function getCompassMarks() : boolean;
    function setCompassMarks(f : boolean) : void;
}

declare namespace Oculars {
    // function updateLists();
    // function ccdRotationReset();
    // function decrementCCDIndex();
    // function decrementOcularIndex();
    // function decrementTelescopeIndex();
    // function decrementLensIndex();
    // function displayPopupMenu();
    // function enableOcular(b:boolean);
    // function getEnableOcular();
    // function incrementCCDIndex();
    // function incrementOcularIndex();
    // function incrementTelescopeIndex();
    // function incrementLensIndex();
    // function disableLens();
    // function rotateCCD(i:number);
    // function getSelectedCCDRotationAngle();
    function setSelectedCCDRotationAngle(d:number):void;
    // function selectCCDAtIndex(i:number);
    // function getSelectedCCDIndex();
    // function selectOcularAtIndex(i:number);
    // function getSelectedOcularIndex();
    // function selectTelescopeAtIndex(i:number);
    // function getSelectedTelescopeIndex();
    // function selectLensAtIndex(i:number);
    // function getSelectedLensIndex();
    // function toggleCCD(b:boolean);
    // function toggleCCD();
    // function getEnableCCD();
    // function toggleCrosshairs(b:boolean);
    // function toggleCrosshairs();
    // function getEnableCrosshairs();
    // function toggleTelrad(b:boolean);
    // function getEnableTelrad();
    // function toggleTelrad();
    // function enableGuiPanel(b:boolean);
    // function enableGuiPanel();
    function getFlagGuiPanelEnabled():boolean;
    function setFlagDMSDegrees(b:boolean):void;
    function getFlagDMSDegrees():boolean;
    function setFlagRequireSelection(b:boolean):void;
    function getFlagRequireSelection():boolean;
    function setFlagLimitMagnitude(b:boolean):void;
    function getFlagLimitMagnitude():boolean;
    function setFlagInitFovUsage(b:boolean):void;
    function getFlagInitFovUsage():boolean;
    function setFlagInitDirectionUsage(b:boolean):void;
    function getFlagInitDirectionUsage():boolean;
    function setFlagAutosetMountForCCD(b:boolean):void;
    function getFlagAutosetMountForCCD():boolean;
    function setFlagScalingFOVForTelrad(b:boolean):void;
    function getFlagScalingFOVForTelrad():boolean;
    function setFlagUseSemiTransparency(b:boolean):void;
    function getFlagUseSemiTransparency():boolean;
    function setFlagShowResolutionCriterions(b:boolean):void;
    function getFlagShowResolutionCriterions():boolean;
    function setArrowButtonScale(d:number):void;
    function getArrowButtonScale():number;
    function setFlagHideGridsLines(b:boolean):void;
    function getFlagHideGridsLines():boolean;
    function setFlagScaleImageCircle(b:boolean):void;
    function getFlagScaleImageCircle():boolean;
    function setFlagShowOcularsButton(b:boolean):void;
    function getFlagShowOcularsButton():boolean;
}

declare namespace Satellites {
    // function tleUpdateComplete(int,int,int,int);
    // function enableInternetUpdates(b:boolean);
    // function enableInternetUpdates();
    // function enableAutoAdd(b:boolean);
    // function enableAutoAdd();
    // function enableAutoRemove(b:boolean);
    // function enableAutoRemove();
    function setFlagHints(b:boolean):void;
    function setFlagLabels(b:boolean):void;
    function setFlagRelisticMode(b:boolean):void;
    function setFlagHideInvisibleSatellites(b:boolean):void;
    function setLabelFontSize(i:number):void;
    function setUpdateFrequencyHours(i:number):void;
    // function updateFromOnlineSources();
    function setOrbitLinesFlag(b:boolean):void;
    // function recalculateOrbitLines();
    // function displayMessage(s:string,QString);
    // function displayMessage(s:string);
    // function saveCatalog(s:string);
    // function saveCatalog();
    function setIridiumFlaresPredictionDepth(i:number):void;
}

declare namespace Exoplanets {
    // function jsonUpdateComplete()
    // function updateJSON()
    function setFlagShowExoplanets(b:boolean):void;
    function getFlagShowExoplanets():boolean;
    function setFlagShowExoplanetsDesignations(b:boolean):void;
    function getFlagShowExoplanetsDesignations():boolean;
    function setFlagShowExoplanetsButton(b:boolean):void;
    function getFlagShowExoplanetsButton():boolean;
    // function getDisplayMode()
    function setDisplayMode(b:boolean):void;
    // function getTimelineMode()
    function setTimelineMode(b:boolean):void;
    function getHabitableMode():boolean;
    function setHabitableMode(b:boolean):void;
    // function getMarkerColor(b:boolean)
    // function setMarkerColor(Vec3f,bool)
    // function getCountPlanetarySystems()
    // function getCountAllExoplanets()
    // function getCountHabitableExoplanets()
    // function setCurrentTemperatureScale(TemperatureScale)
    // function getCurrentTemperatureScale()
    // function getCurrentTemperatureScaleKey()
    function setCurrentTemperatureScaleKey(s:string):void;
}